import type { TwTheme } from 'twrnc/dist/esm/tw-config';

export const LightTheme: TwTheme = {
  colors: {
    transparent: 'transparent',
    primary: '#006688',
    'on-primary': '#FFFFFF',
    'on-primary-variant': '#FFFFFFD0',
    'primary-container': '#E0F3FF',
    'on-primary-container': '#001E2B',
    secondary: '#B82000',
    'secondary-variant': '#c17d70',
    'on-secondary': '#FFFFFF',
    'secondary-container': '#FFDAD1',
    'on-secondary-container': '#3F0400',
    error: '#B3261E',
    'on-error': '#FFFFFF',
    'error-container': '#F9DEDC',
    'on-error-container': '#410E0B',
    background: '#FFFBF7',
    'on-background': '#1D1B16',
    surface: '#FFFBFE',
    'on-surface': '#1D1B16',
    outline: '#79747E',
    'outline-variant': '#bebebe',
  },
};

export const DarkTheme: TwTheme = {
  colors: {
    transparent: 'transparent',
    primary: '#6ED2FF',
    'on-primary': '#003549',
    'on-primary-variant': '#003549D0',
    'primary-container': '#004D68',
    'on-primary-container': '#BEE8FF',
    secondary: '#FFB4A2',
    'secondary-variant': '#bcaeab',
    'on-secondary': '#650B00',
    'secondary-container': '#8D1400',
    'on-secondary-container': '#FFDAD1',
    error: '#F2B8B5',
    'on-error': '#601410',
    'error-container': '#8C1D18',
    'on-error-container': '#F9DEDC',
    background: '#2C2C2C',
    'on-background': '#E8E2D9',
    surface: '#2C2C2C',
    'on-surface': '#E8E2D9',
    outline: '#938F99',
    'outline-variant': '#938F99DE',
  },
};
